"""
Tests for verifying the Calculator.add functionality using Faker for generating random data.
"""

from faker import Faker
from app.calculator import Calculator

def test_faker_add():
    """Test Calculator.add using random integers generated by Faker."""
    fake = Faker()
    num1 = fake.random_int(min=1, max=100)
    num2 = fake.random_int(min=1, max=100)
    result = Calculator.add(num1, num2)
    # Assert that the result is the sum of the two numbers
    assert result == num1 + num2
